### PR TITLE
Custom thumbnail

### PR DESCRIPTION
**Pull request by iefserge**
R = @kesla @ellell 
T = minor

### CODE REVIEW

**Comment by kesla** [comment]
For clarity I'd go with a `thumbnail` property.

**Comment by kesla** [comment]
other than that LGTM

**Comment by ellell** [comment]
Yea, I'm for using `thumbnail` property also, other than that 👍

**Comment by iefserge** [comment]
@kesla @ellell there is already a thumbnail property for image URL.

**Comment by kesla** [comment]
ok so yeah then I'd use `customThumbnail` or something. I still think that being explicit here would be preferred.

**Pull request merged**
